name: README build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "5 8 * * 0" # Every Sunday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Main branch
        uses: actions/checkout@v2
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-js-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-js-
      - name: Install dependencies
        run: npm ci
      - name: Generate README file
        run: node index.js
      - name: Commit and Push new README.md to the repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README.md
          commit_options: "--no-verify"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
